jwt:
  secretKey: ljhaowuefqjhoib876rousdghckjgsfbco8a374t o8bchegliuCHFJSDFHBoiqf

spring:
  application:
    name: api-gateway

#api gateway config
  cloud:
    gateway:
      routes:
        - id: order-service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/api/v1/orders/**
          filters:
            - StripPrefix=2
#            - RedirectTo=302, http://codingshuttle.com
            - name: LoggingOrdersFilter
            - name: Authentication
              args:
                isEnabled: true
        - id: inventory-service
          uri: lb://INVENTORY-SERVICE
          predicates:
            - Path=/api/v1/inventory/**
          filters:
            - StripPrefix=2
            - AddRequestHeader=X-Custom-Header, Manoj
            - name: Authentication
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka