management:
  health:
    circuitBreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

resilience4j:
  retry:
    configs:
      default:
        maxRetryAttempts: 3
        waitDuration: 100ms
    instances:
      inventoryRetry:
        baseConfig: default
        waitDuration: 200ms

  ratelimiter:
    instances:
      inventoryRateLimiter:
        limitRefreshPeriod: 1s # Refresh the limit every 5 second
        limitForPeriod: 100      # Max 2 calls in a refresh period
        timeoutDuration: 10ms    # Time to wait for permission before a request fails

  circuitbreaker:
    instances:
      inventoryCircuitBreaker:
        registerHealthIndicator: true  # Expose circuit breaker health via the actuator
        slidingWindowSize: 10          # Size of the sliding window for call recording
        slidingWindowType: COUNT_BASED # Use count based sliding window
        minimumNumberOfCalls: 10       # Minimum number of calls before calculating failure rate
        failureRateThreshold: 50       # if 50% (5 out of 10) calls fails, the circuit goes to open state
        waitDurationInOpenState: 1s   # time the circuit stays OPEN before going into HALF_OPEN state
        permittedNumberOfCallsInHalfOpenState: 3 # Number of test calls in HALF_OPEN state
        eventConsumerBufferSize: 10    # Buffer size for event logs
